model_list:
  # model_name は任意の名前を設定できる
  - model_name: "claude-3-5-sonnet-us"
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: us-east-1
  - model_name: "claude-3-5-sonnet-apac"
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: ap-southeast-2
  - model_name: "claude-3-7-sonnet-us"
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: us-east-1

litellm_settings:
  drop_params: True
  num_retries: 0
  request_timeout: 600
  # このモデルが使えなかったら、こっちのモデルを使いたい、という Fallback 設定を記載
  fallbacks: [
    {"claude-3-5-sonnet-us": ["claude-3-5-sonnet-apac"]},
    {"claude-3-7-sonnet-us": ["claude-3-5-sonnet-apac", "claude-3-5-sonnet-us"]},
    {"claude-3-5-sonnet-apac": ["claude-3-7-sonnet-us"]}
  ]